Dashboard user statistics
parmonov98/devstart-api pull request #14
Opened 2023-07-24 06:44 UTC by abror9109

2023-07-24 07:00 UTC, akbarali1 requested changes
user modelga developer va idealHolder degan scope uchun koemnt yozish kerak shunda u funksiyalarni ishlatganda undefined bermaydi

2023-07-24 07:00 UTC, akbarali1 commented on app/Models/User.php
>  }
Scopelar uchun modelda commentlarni qoldirish kerak

2023-07-24 07:00 UTC, akbarali1 commented on app/Models/User.php
>  }
Topilmagan funksiya bo`lmasligi uchun

2023-07-24 07:29 UTC, akbarali1 requested changes
Komentlarni o`zgartirish kerak

2023-07-24 07:29 UTC, akbarali1 commented on app/Models/User.php
>   * @property bool|null $is_admin
bool|null menimcha xato 


?bool

bo`lishi kerak

2023-07-24 07:29 UTC, akbarali1 commented on app/Models/User.php
> + * @method static Builder developer()
scope relation va property lar orasida joy tashlangan bo`lishi kerak

2023-07-24 08:29 UTC, akbarali1 approved these changes

2023-07-26 10:23 UTC, Lanser0614 reviewed
To'g'irlash kere

2023-07-26 10:23 UTC, Lanser0614 commented on app/Models/User.php
> -// use Illuminate\Contracts\Auth\MustVerifyEmail;
cs fix i zapusk qilin

2023-07-26 10:23 UTC, Lanser0614 commented on app/Models/User.php
> +    public function scopeDeveloper($query): Builder
scopeWhereDeveloper

2023-07-26 10:23 UTC, Lanser0614 commented on app/Models/User.php
> +    public function scopeIdeaHolder($query): Builder
scopeWhereIdeaHolder

2023-07-27 16:46 UTC, merged